version: '3.8'

services:
  # Tên dịch vụ
  redis:
    # Lấy ảnh (image) Redis mới nhất
    image: redis:latest
    # Tên container (tùy chọn nhưng nên có)
    container_name: my-redis-db
    # Ánh xạ cổng:
    # Cổng 6379 bên trong container -> ra cổng 6379 ở máy thật (localhost)
    ports:
      - "6379:6379"
    restart: unless-stopped